"""Baseline — mark existing schema as up-to-date.

Revision ID: 20260422_0000_baseline
Revises:
Create Date: 2026-04-22

Purpose
-------
At the time Alembic was introduced, every SQLAlchemy table in ``model/`` was
already created imperatively via ``Base.metadata.create_all`` in main.py
lifespan. This baseline migration is intentionally a **no-op** — it exists so
future autogenerated revisions have a parent to chain off.

Convention for downstream migrations
------------------------------------
* Always review autogenerated SQL before committing — Alembic can't infer
  every MySQL-specific nuance (e.g. CHARACTER SET utf8mb4).
* For data-only migrations, use explicit ``op.execute(text(...))`` blocks.
* Never mix schema + data changes in a single revision — separate concerns so
  one can be reverted without touching the other.
"""
from typing import Sequence, Union

from alembic import op  # noqa: F401  — kept so future edits have it in scope
import sqlalchemy as sa  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "20260422_0000_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # No-op baseline: the existing tables were created by SQLAlchemy's
    # ``Base.metadata.create_all`` prior to Alembic adoption.
    pass


def downgrade() -> None:
    # Downgrade of baseline is meaningless — the schema existed before
    # Alembic was in the picture. Refuse to do anything destructive.
    pass
